spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/board
    username: root
    password: g5a44t
    jpa:
      hibernate:
        ddl-auto: create
  profiles:
    include: API-KEY,secret
  jwt:
    secret:
      lasdkfjadkfj@343kjsdfklj!dlsdjfospvckjafe9r$%#$@dskjfkjcvxkjfla!!@dskjfksjfasdfjjk23490e@#@fdsjal!